name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.42"

      - id: determine_release_tag
        name: Determine release tag
        run: |
          if [[ $GITHUB_REF = refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
          else
            tag="$(git describe --tags --abbrev=0)"
          fi

          echo "TAG=$tag" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build and Release
        run: script/build_and_release.sh
        env:
          GH_RELEASE_TAG: ${{ steps.determine_release_tag.outputs.TAG }}
        shell: bash
