name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.42"

      - name: Build
        run: script/build.sh

      - name: Release
        # run: gh release create "$GH_RELEASE_TAG" $prerelease $draft_release --title="${GH_RELEASE_TAG#v}" --generate-notes -- "${assets[@]}"
        run: gh release create "$GH_RELEASE_TAG" ./dist/*
        env:
          GH_TOKEN: ${{ github.token }}
